package services

import "strings"

// careTranslation 植物养护描述的英文→中文翻译映射。
// 由 buildGuide 在生成 guide 时调用，确保新同步的植物自动使用中文描述。
// key: 维度名（浇水/光照/土壤/施肥/修剪），value: 英文→中文映射。
var careTranslation = map[string]map[string]string{
	"浇水": {
		"2-3 times weekly": "每周浇水 2-3 次",
		"Do not water frequently; maintain dryness; stop watering during summer dormancy.": "不宜频繁浇水；保持干燥；夏季休眠期停止浇水。",
		"Drought-tolerant; 土壤干透后浇水; 冬季减少浇水.": "耐旱，土壤干透后浇透；冬季减少浇水。",
		"Likes wet environments; keep soil moist; may spray water or rub leaves with water.": "喜湿润环境，保持土壤湿润；可向叶片喷水保湿。",
		"Likes wet environments; 浇透水 when soil is dry; rub leaves with water in summer.": "喜湿润环境，土壤干透后浇透；夏季可擦拭叶片保湿。",
		"Likes wet enviros; water when soil dry; mist leaves when dry.": "喜湿润环境，土壤干透后浇水；干燥时向叶片喷雾。",
		"Likes wet envs; sprays water for moisture; 冬季减少浇水.": "喜湿润环境，喷水保湿；冬季减少浇水。",
		"Likes wet envs; water when soil dries, mist leaves often in summer.": "喜湿润环境，土壤干透后浇水；夏季多向叶片喷雾。",
		"Likes wet envs; water when soil dries; mist air/leaves; reduce water in winter; keep soil moist.": "喜湿润环境，土壤干透后浇水；经常向空气和叶片喷雾；冬季减少浇水；保持土壤湿润。",
		"Maintain soil moisture": "保持土壤湿润",
		"Moderately drought-resistant; keep soil moist; water every 1-2 days in summer, 3-6 days in autumn and winter.": "较耐旱，保持土壤湿润；夏季每 1-2 天浇一次，秋冬每 3-6 天浇一次。",
		"Moderately drought-resistant; 浇透水 when dry; mist to keep moist.": "较耐旱，干透后浇透；喷雾保持湿度。",
		"Moderately drought-resistant; 浇透水 when soil is dry, and increase frequency in summer.": "较耐旱，土壤干透后浇透；夏季增加浇水频率。",
		"Needs lots of water in April to May; reduce in summer and winter.": "四五月份需水量大；夏季和冬季减少浇水。",
		"Not drought-resistant; 土壤干透后浇水.": "不耐旱，土壤干透后即浇。",
		"Prefers wet environments but reduce watering and fertilization in winter; avoid saturated soil.": "喜湿润环境，但冬季需减少浇水和施肥；避免土壤积水。",
		"Prefers wet environments; keep soil moist; water every 1-2 days in summer, every 3-5 days in autumn and winter.": "喜湿润环境，保持土壤湿润；夏季每 1-2 天浇一次，秋冬每 3-5 天浇一次。",
		"Prefers wet environments; 浇透水 when soil is dry; avoid saturated conditions.": "喜湿润环境，土壤干透后浇透；避免积水。",
		"Soil should be watered when its surface becomes dry.": "土壤表面干了就浇。",
		"Stop water during decrustation in spring; reduce in summer; keep soil moist in autumn for peak growth.": "春季脱皮期停止浇水；夏季减少浇水；秋季保持土壤湿润以促进生长。",
		"Thoroughly water plant when topsoil feels dry to the touch and prevent overwatering that may lead to root rot.": "表土摸起来干了就浇透，但要避免浇水过多导致烂根。",
		"Thrives in wet environments; water when soil dries, may mist leaves.": "喜湿润环境，土壤干透后浇水，可向叶片喷雾。",
		"Water 2 times in summer, 20ml each, keep soil moist otherwise, 浇透水 when dry.": "夏季每周浇 2 次，每次 20ml，其余时间保持土壤湿润，干透后浇透。",
		"Water deeply but infrequently, and less often in the dormant period, while watering more regularly during hot seasons.": "少量多次深浇，休眠期减少浇水，炎热季节规律浇水。",
		"Water deeply when soil surface is dry; 避免积水.": "土壤表面干了就深浇；避免积水。",
		"Water every 10-15 days; maintain a dry environment.": "每 10-15 天浇一次；保持干燥环境。",
		"Water every 7-10 days; keep dry.": "每 7-10 天浇一次；保持干燥。",
		"Water only when soil is dry; reduce during flowering; 1-2 times weekly.": "土壤干了再浇；花期减少浇水；每周 1-2 次。",
		"Water soil thoroughly when it dries out.": "土壤干透后浇透。",
		"Water soil timely and ensure proper drainage.": "及时浇水并确保排水良好。",
		"Water sparingly, every 7-10 days; avoid water during dormancy.": "少量浇水，每 7-10 天一次；休眠期避免浇水。",
		"Water thoroughly every 5-7 days; submerge soil if needed. Sprinkle water in the air in summer.": "每 5-7 天浇透一次；必要时浸盆；夏季向空中喷水。",
		"Water thoroughly only when soil is dry, every 4-5 days": "仅在土壤干透后浇透，每 4-5 天一次",
		"Water thoroughly when dry; water 30-50 ml daily in summer.": "干透后浇透；夏季每天浇水 30-50ml。",
		"Water thoroughly when dry; water daily in summer.": "干透后浇透；夏季每天浇水。",
		"Water thoroughly when soil is dry, like with wet environments.": "喜湿润环境，土壤干透后浇透。",
		"Water thoroughly when soil is dry; mist when humidity < 30%.": "土壤干透后浇透；空气湿度低于 30% 时喷雾。",
		"Water thoroughly when soil is dry; water daily in summer; reduce in winter.": "土壤干透后浇透；夏季每天浇水；冬季减少浇水。",
		"Water thoroughly when soil surface is dry; 避免浇水过多.": "土壤表面干了就浇透；避免浇水过多。",
		"Water twice in summer; keep moist otherwise; 土壤干透后浇水": "夏季每周浇两次；其余时间保持湿润；土壤干透后浇水",
		"Water when soil dries, 避免积水.": "土壤干了就浇，避免积水。",
		"Water when soil is dry, reduce in summer, cut back on water and fertilizer.": "土壤干了再浇，夏季减少浇水，同时减少施肥。",
		"Water when soil is dry.": "土壤干了再浇。",
		"Water when soil is dry; mist leaves with water in summer to retain moisture.": "土壤干了再浇；夏季向叶片喷水保湿。",
		"Water when soil is dry; reduce in summer and winter.": "土壤干了再浇；夏冬两季减少浇水。",
		"Water when soil is dry; reduce in winter.": "土壤干了再浇；冬季减少浇水。",
		"Water when soil is dry; reduce winter watering.": "土壤干了再浇；冬季减少浇水。",
		"Water when soil is dry; shorten summer dormancy; reduce watering.": "土壤干了再浇；缩短夏季休眠期；减少浇水。",
		"Water when soil is dry; 夏季减少浇水.": "土壤干了再浇；夏季减少浇水。",
		"Water when soil is dry; 避免积水.": "土壤干了再浇；避免积水。",
		"Water when soil surface is dry.": "土壤表面干了就浇。",
		"保持土壤湿润 only.": "保持土壤湿润即可。",
		"保持土壤湿润; reduce watering during summer dormancy.": "保持土壤湿润；夏季休眠期减少浇水。",
		"保持土壤湿润; 浇透水 when dry; reduce water in winter.": "保持土壤湿润；干透后浇透；冬季减少浇水。",
		"喜湿润环境; keep relatively moist, 冬季减少浇水.": "喜湿润环境，保持相对湿润；冬季减少浇水。",
		"耐旱; keep soil moist, 浇透水 when dry.": "耐旱，保持土壤湿润，干透后浇透。",
		"耐旱; water every 4-5 days in summer, every 8-10 days in winter.": "耐旱；夏季每 4-5 天浇一次，冬季每 8-10 天浇一次。",
		"耐旱; water when soil dries, 避免浇水过多.": "耐旱，土壤干了再浇；避免浇水过多。",
		"耐旱; 浇透水 when soil is dry, 避免浇水过多.": "耐旱，土壤干透后浇透；避免浇水过多。",
		"耐旱，土壤干透后浇水; reduce watering during dormancy": "耐旱，土壤干透后浇水；休眠期减少浇水",
		"耐旱，土壤干透后浇水; reduce watering in hot summer.": "耐旱，土壤干透后浇水；炎热的夏季减少浇水。",
		"耐旱，土壤干透后浇水; reduce winter watering.": "耐旱，土壤干透后浇水；冬季减少浇水。",
		"耐旱，土壤干透后浇水; 夏季减少浇水 and winter.": "耐旱，土壤干透后浇水；夏季和冬季减少浇水。",
	},
	"光照": {
		"Avoid bright 阳光直射, especially at noon in the summer months, but also tolerate 半阴 and avoid weak light conditions which can lead to overgrowth.": "避免阳光直射，尤其是夏季正午；耐半阴，但避免光照不足导致徒长。",
		"Avoid high temperatures and 阳光直射 in summer.": "夏季避免高温和阳光直射。",
		"Avoid scorching light as you would avoid intense sunshine.": "避免强光灼伤，如同避开烈日暴晒。",
		"Avoid scorching light; prefer moderate light.": "避免强光；喜柔和光照。",
		"Avoid strong direct light in summer; tolerate 3-4 hours of sun in winter.": "夏季避免强光直射；冬季可接受 3-4 小时直射光。",
		"Avoid strong direct light; place in 散射光 areas.": "避免强光直射；放置于散射光处。",
		"Avoid strong 阳光直射; prefer mild sunlight.": "避免强烈阳光直射；喜柔和光照。",
		"Before flowering, put under gentle sunlight; during flowering, place in 散射光.": "花前置于柔和阳光下；花期放置于散射光处。",
		"Can grow in bright 散射光 like half-shade.": "可在明亮散射光环境下生长，类似半阴环境。",
		"Durable in shaded areas; place in 散射光.": "耐阴性强；放置于散射光处。",
		"Enjoy adequate sunlight; avoid strong 阳光直射 in summer; tolerate half-shade; may enter dormancy.": "喜充足光照；夏季避免强光直射；耐半阴；可能会休眠。",
		"Enjoy ample sunlight, no dormant period, avoid intense light in summer.": "喜充足光照，无明显休眠期，夏季避免强光。",
		"Enjoy ample sunlight, tolerates 半阴": "喜充足光照，耐半阴",
		"Enjoy mild sunlight; avoid strong light.": "喜柔和光照；避免强光。",
		"Enjoy sunlight; resistant to half-shade; temporary dormancy in summer; planted in half-shade": "喜阳光，不耐半阴；夏季短暂休眠；种植于半阴环境",
		"Enjoy sunlight; tolerates half shade.": "喜阳光，耐半阴。",
		"Grows in sunny places like sunshine, tolerating shade as well.": "喜阳光充足环境，也耐阴。",
		"Grows in sunny places like sunshine.": "喜阳光充足环境。",
		"High-quality fruits in sunny places like sunshine": "喜阳光充足环境以结出优质果实",
		"In summer provide shade as needed; in winter keep in direct light indoors.": "夏季根据需要遮阴；冬季室内保持充足光照。",
		"In winter, a half-shaded area typically requires 2-3 hours of 阳光直射.": "冬季半阴环境下通常需要 2-3 小时光照。",
		"Its inactive time is summer; provide 半阴 for proper care. Spring and autumn are when it thrives, requiring 全日照 exposure.": "夏季为其休眠期，需半阴养护；春秋为生长期，需全日照。",
		"Like adequate sunlight, no apparent dormant period": "喜充足光照，无明显休眠期",
		"Like sunlight, place in sunny spots": "喜阳光，放置于光照充足处",
		"Like sunshine, a brief summer dormancy; half-shade is better for care.": "喜阳光，夏季短暂休眠；半阴养护更佳。",
		"Like sunshine, dormant in summers' high heat, placed in 散射光.": "喜阳光，夏季高温时休眠，放置于散射光处。",
		"Like sunshine, dormant in winter under low temperatures, not fearing strong light.": "喜阳光，冬季低温时休眠，不惧强光。",
		"Like sunshine, no dormant period needed; shade for summer strong light.": "喜阳光，无明显休眠期；夏季强光时需遮阴。",
		"Like sunshine, no visible dormancy": "喜阳光，无明显休眠迹象",
		"Like sunshine, not shade-resistant": "喜阳光，不耐阴",
		"Like sunshine, place in sunny spots and shade during summer when dormant.": "喜阳光，放置于光照充足处，夏季休眠期需遮阴。",
		"Like sunshine, place in sunny spots and shade under summer's bright light.": "喜阳光，放置于光照充足处，夏季强光时遮阴。",
		"Like sunshine, slight shade tolerated": "喜阳光，稍耐阴",
		"Like sunshine, strongly resistant to shade": "喜阳光，不耐阴",
		"Likes adequate light; use half-shade in summer for better care.": "喜充足光照；夏季半阴养护更佳。",
		"Likes adequate sunshine; half-dormant in summer; place in 散射光.": "喜充足阳光；夏季半休眠；放置于散射光处。",
		"Likes ample sun, tolerates strong light, can briefly go dormant in summer; reduce watering and provide some shade then.": "喜充足阳光，耐强光，夏季可短暂休眠；届时减少浇水并适当遮阴。",
		"Likes half-shade, tolerates 散射光, strongly shade-resistant": "喜半阴环境，散射光下生长良好，不耐阴",
		"Likes half-shade; tolerates 4-5 hours of moderate light.": "喜半阴；可耐受 4-5 小时中等光照。",
		"Likes light but tolerates slight shade; avoid scorching light.": "喜光但稍耐阴；避免强光灼伤。",
		"Likes light, avoid strong sun, dormant in hot summers, place in filtered light.": "喜光，避免强光，夏季高温休眠，放置于散射光处。",
		"Likes light, needs brief summer and winter dormancy, place in bright, 散射光.": "喜光，夏冬两季短暂休眠，放置于明亮散射光处。",
		"Likes light, tolerates half-shade, dorms in hot summers, place in 散射光": "喜光，耐半阴，夏季高温休眠，放置于散射光处",
		"Likes light, tolerates half-shade; needs short summer dormancy; benefits from half-shade care.": "喜光，耐半阴；夏季短暂休眠；半阴养护更佳。",
		"Likes light; no dormant period; shade for summer sunlight": "喜光，无明显休眠期；夏季需遮阴",
		"Likes light; put in sunny places in 春秋两季, in summer place in a cool, ventilated area.": "喜光；春秋两季放置于阳光充足处，夏季放在凉爽通风处。",
		"Likes light; tolerates summer shade; no dormant period.": "喜光；夏季可遮阴；无明显休眠期。",
		"Likes moderate light, tolerant of half-shade; dormant in summer heat; place in 散射光.": "喜中等光照，耐半阴；夏季高温休眠；放置于散射光处。",
		"Likes moderate light; place in bright, indirect spots; 避免阳光直射.": "喜中等光照；放置于明亮散射光处；避免阳光直射。",
		"Likes moderate sunshine; needs shade in strong summer light.": "喜中等光照；夏季强光时需遮阴。",
		"Likes sunlight; tolerate some shade; avoid intense sun.": "喜阳光；稍耐阴；避免强光暴晒。",
		"Long-day plant, place in sunny spots": "长日照植物，放置于光照充足处",
		"Long-day plant; place in sunny spots, avoid intense noon sunlight.": "长日照植物；放置于光照充足处，避免正午强光。",
		"Place during 生长季 in half-shade areas; avoid direct strong sun in summer.": "生长期置于半阴处；夏季避免强光直射。",
		"Place in areas with bright 散射光": "放置于散射光明亮处",
		"Place in areas with bright 散射光 during summer.": "夏季放置于散射光明亮处。",
		"Place in areas with diffuse lighting": "放置于散射光环境",
		"Place in areas with 散射光 like shaded environments.": "放置于散射光或阴凉环境。",
		"Place in sunny spots; avoid strong noon sun; fewer flowers with less light.": "放置于光照充足处；避免正午强光；光照不足会减少开花。",
		"Place in sunny spots; thrives with 散射光.": "放置于光照充足处；散射光下生长良好。",
		"Place in sunny spots; tolerates half-shade; becomes dormant in hot summers.": "放置于光照充足处；耐半阴；夏季高温休眠。",
		"Place in 散射光; needs 3-5 hours of light for flowering.": "放置于散射光处；需 3-5 小时光照才能开花。",
		"Prefers ample sunshine but needs shade in midsummer during intense light.": "喜充足阳光，但仲夏强光时需遮阴。",
		"Prefers bright, 散射光.": "喜明亮散射光。",
		"Prefers bright, 散射光; 耐阴.": "喜明亮散射光；耐阴。",
		"Prefers cool, wet spots with some sunlight; may shade a bit.": "喜凉爽湿润且有适量阳光的环境；可适当遮阴。",
		"Prefers half-shade, tolerates 3-4 hours of moderate sunlight.": "喜半阴环境，可耐受 3-4 小时中等光照。",
		"Prefers half-shade; avoid 阳光直射 in summer; increase light in other seasons.": "喜半阴；夏季避免阳光直射；其他季节增加光照。",
		"Prefers half-shade; avoids 阳光直射, place in area with 散射光.": "喜半阴；避免阳光直射，放置于散射光处。",
		"Prefers half-shade; thrives in 散射光.": "喜半阴；散射光下生长良好。",
		"Prefers half-shade; thrives with bright, 散射光.": "喜半阴；明亮散射光下生长良好。",
		"Prefers light, semi-dormant in hot summers; place in 散射光.": "喜光，夏季高温时半休眠；放置于散射光处。",
		"Prefers light, shows no sign of dormancy.": "喜光，无休眠迹象。",
		"Prefers light; avoids strong light": "喜光；避免强光",
		"Prefers light; dormant in hot summers; place in 散射光.": "喜光，夏季高温休眠；放置于散射光处。",
		"Prefers mild sun exposure while avoiding intense 阳光直射.": "喜温和阳光，避免强烈阳光直射。",
		"Prefers moderate sunlight, tolerates half shade": "喜中等光照，耐半阴",
		"Prefers moderate sunshine, avoid direct strong light, tolerates slight shade.": "喜中等光照，避免强光直射，稍耐阴。",
		"Prefers strong light; place in sunny spots.": "喜强光；放置于光照充足处。",
		"Prefers sunshine but needs shade in strong summer light": "喜阳光，但夏季强光时需遮阴",
		"Prefers sunshine, avoids strong direct light": "喜阳光，避免强光直射",
		"Prefers 半阴 but tolerates locations with dappled brightness and can sometimes receive up to 3 hours of 阳光直射 during the winter months.": "喜半阴环境，但可耐受斑驳明亮光线，冬季偶尔可接受最多 3 小时直射光。",
		"Provide a half-shade environment with scattered sunlight.": "提供散射光的半阴环境。",
		"Provide warmth and filtered illumination.": "提供温暖和散射光照环境。",
		"Relatively shade-tolerant, prefers half-shade; leaves stay fresh and green in winter with some sun.": "较耐阴，喜半阴；冬季有适量阳光可保持叶片常绿。",
		"Relatively shade-tolerant; prefers half-shade environments.": "较耐阴；喜半阴环境。",
		"Requires ample light, tolerates 半阴": "需充足光照，耐半阴",
		"Requires 半日照light; direct intense light must be avoided, especially during seedling and flowering phases when it prefers diffused bright illumination.": "需半日照光照；避免强光直射，尤其在苗期和花期更喜散射明亮光照。",
		"Resist shade well; ideally placed in areas with fragmented lighting.": "耐阴性好；理想放置于散射光环境。",
		"Resistant to semi-shade; place in 散射光 areas.": "耐半阴；放置于散射光处。",
		"Resistant to shade; place in 散射光 in summer; allow 3-4 hours of sun in winter.": "耐阴；夏季放置于散射光处；冬季可接受 3-4 小时光照。",
		"Resistant to shade; place in 明亮散射光; allow 2-3 hours of sunlight in winter.": "耐阴；放置于明亮散射光处；冬季可接受 2-3 小时光照。",
		"Shade works well under strong summer sunlight.": "夏季强光下遮阴效果好。",
		"Shade works well under summer strong light but needs 全日照 in winter.": "夏季强光时遮阴效果好，但冬季需全日照。",
		"Shade-tolerant plants: bright 散射光, avoid sun exposure": "耐阴植物：明亮散射光，避免暴晒",
		"Short summer dormancy; prefer half-shade; grows best in 春秋两季 with ample sunshine.": "夏季短暂休眠；喜半阴；春秋两季在充足阳光下生长最好。",
		"Similar sufficient sunlight": "需充足光照",
		"Similar to half-shade, bright 散射光": "类似半阴环境，需明亮散射光",
		"Summer is dormant; use shade. Spring and autumn grow; need sunshine.": "夏季休眠，需遮阴。春秋生长期需充足阳光。",
		"Take more sunlight in 春秋两季; scatter light in summer.": "春秋两季多晒太阳；夏季散射光。",
		"Tolerates half-shade, prefers moderate sunlight, avoid direct strong light.": "耐半阴，喜中等光照，避免强光直射。",
		"Use half-shade for care; place in 散射光 areas.": "半阴养护；放置于散射光处。",
		"likes shade; can place in bright, 散射光": "喜阴；可放置于明亮散射光处",
		"prefers half-shade, tolerates 2-3 hours of moderate sun": "喜半阴，可耐受 2-3 小时中等光照",
		"喜半阴环境, place in bright, 散射光.": "喜半阴环境，放置于明亮散射光处。",
		"喜阳光 but avoids strong light; bright 散射光 in summer, 全日照 in winter.": "喜阳光但避免强光；夏季明亮散射光，冬季全日照。",
		"喜阳光 but needs shade under strong summer light; may require 4-6 hours of sun daily.": "喜阳光但夏季强光时需遮阴；每天可能需要 4-6 小时光照。",
		"喜阳光 but tolerates half-shade for better summer care.": "喜阳光但耐半阴，夏季半阴养护更佳。",
		"喜阳光, avoids direct strong light, tolerates half shade": "喜阳光，避免强光直射，耐半阴",
		"喜阳光, enters dormancy in hot summers, prefers some shade for better care.": "喜阳光，夏季高温时进入休眠，适当遮阴养护更佳。",
		"喜阳光, tolerates half-shade; needs short summer dormant period; benefits from half-shade care.": "喜阳光，耐半阴；夏季短暂休眠；半阴养护更佳。",
		"喜阳光, 耐阴; thrive in sunny spots; 避免阳光直射.": "喜阳光，耐阴；在阳光充足处生长良好；避免阳光直射。",
		"喜阳光; place in sunny spots; avoid strong sun in summer midday.": "喜阳光；放置于光照充足处；避免夏季正午强光。",
		"喜阳光; relatively tolerant of half-shade; needs a short summer dormancy; prefer half-shade for better care": "喜阳光；较耐半阴；夏季短暂休眠；半阴养护更佳",
		"喜阳光; tolerates half shade": "喜阳光；耐半阴",
	},
	"土壤": {
		"80% peat, 20% perlite": "80% 泥炭 + 20% 珍珠岩",
		"Fertile soil or special humus soil": "肥沃土壤或专用腐殖土",
		"Fertile, loose, well-drained loam soil": "肥沃疏松、排水良好的壤土",
		"Loamy sand": "壤质沙土",
		"Loose soil or special humus soil": "疏松土壤或专用腐殖土",
		"No strict soil requirements": "对土壤要求不严",
		"No strict soil requirements; prefers sandy loam.": "对土壤要求不严，偏好沙质壤土。",
		"Peat mixed with coarse sand or hydroponics": "泥炭混合粗砂，或水培",
		"Peat mixed with coarse sand or nutrient-rich soil": "泥炭混合粗砂或营养丰富的土壤",
		"Peat mixed with perlite": "泥炭混合珍珠岩",
		"Peat or soil with added humus": "泥炭或添加腐殖质的土壤",
		"Peat, soil with nutrients, or hydroponics": "泥炭、营养土或水培均可",
		"Prefers slightly alkaline soil; add peat with a bit of lime or baking soda.": "喜微碱性土壤；可添加少量泥炭并拌入石灰或小苏打。",
		"Prefers slightly alkaline soil; can add peat, lime, or baking soda.": "喜微碱性土壤；可添加泥炭、石灰或小苏打。",
		"Replace sphagnum moss annually.": "每年更换水苔。",
		"Rich, deep, fertile soil": "深厚肥沃的土壤",
		"Rich, deep, loose soil": "深厚疏松的土壤",
		"Sandy loam or hydroponics": "沙质壤土或水培",
		"Sandy, 微酸性土壤 with a loose texture or specific nutrients": "沙质微酸性土壤，质地疏松或富含特定养分",
		"Soil slightly acidic, loose in texture or rich in specific nutrients": "土壤微酸性，质地疏松或富含特定养分",
		"Soil that is acidic, loose, or rich in specific nutrients": "酸性、疏松或富含特定养分的土壤",
		"Soil with peat or specific nutrients": "含泥炭或特定养分的土壤",
		"Well-drained sandy loam or hydroponic systems": "排水良好的沙质壤土或水培系统",
		"peat with sphagnum moss for moisture retention": "泥炭加水苔以保持水分",
	},
	"施肥": {
		"Apply diluted fertilizers monthly from summer to autumn.": "夏秋两季每月施一次稀薄液肥。",
		"Apply fertilizer every 10-15 days in 春秋两季, avoid winter.": "春秋两季每 10-15 天施肥一次，冬季停肥。",
		"Apply low-concentration fertilizers 1-2 times monthly in spring and summer.": "春夏两季每月施 1-2 次低浓度肥料。",
		"Apply once every 10 days in autumn; stop during ecdysis.": "秋季每 10 天施一次；脱皮期停肥。",
		"Apply sufficient base fertilizer": "施足底肥",
		"Apply 液态肥料s from April to May and September to November, excluding summer and winter.": "四五月及九月至十一月施液态肥，夏冬两季停施。",
		"Dilute and apply fertilizers 2-3 times monthly as directed.": "按说明稀释肥料，每月施 2-3 次。",
		"Dilute and apply fertilizers every 10-15 days.": "按说明稀释肥料，每 10-15 天施一次。",
		"Every 10-15 days": "每 10-15 天施一次",
		"Fertilization not needed much; apply diluted fertilizers monthly in spring as instructed.": "不需大量施肥；春季按说明每月施一次稀薄液肥。",
		"Fertilize 1-2 times/month; reduce in winter.": "每月施肥 1-2 次；冬季减少施肥。",
		"Follow instructions to dilute fertilizers; 每月施1-2次 in spring and summer.": "按说明稀释肥料；春夏每月施 1-2 次。",
		"Monthly top-dressing during vegetative stages": "生长期每月追肥一次",
		"Need more fertilization. Dilute as instructed and apply 2-3 times monthly.": "需较多肥料。按说明稀释，每月施 2-3 次。",
		"Require litter fertilization; apply diluted fertilizers as instructed; 每月施1-2次 from spring to autumn.": "少量施肥；按说明稀释肥料；春秋每月施 1-2 次。",
		"Spray leaves frequently with water in summer. Apply low-concentration fertilizers sparingly in winter.": "夏季多向叶片喷水。冬季少量施用低浓度肥料。",
		"Use base fertilizers, top-dress later.": "先施底肥，后期追肥。",
		"按说明稀释肥料. Apply 液态肥料 every 10-15 days in summer and autumn.": "按说明稀释肥料。夏秋两季每 10-15 天施一次液态肥。",
		"按说明稀释肥料; apply 1-2 times/month during growth; stop in winter.": "按说明稀释肥料；生长期每月施 1-2 次；冬季停肥。",
		"按说明稀释肥料; apply 1-2 times/month, except in summer.": "按说明稀释肥料；每月施 1-2 次，夏季除外。",
		"按说明稀释肥料; apply every 10-15 days in spring and summer.": "按说明稀释肥料；春夏每 10-15 天施一次。",
		"按说明稀释肥料; apply every 10-15 days in spring.": "按说明稀释肥料；春季每 10-15 天施一次。",
		"按说明稀释肥料; apply every 10-15 days in 春秋两季, not in summer.": "按说明稀释肥料；春秋两季每 10-15 天施一次，夏季停肥。",
		"按说明稀释肥料; apply every 10-15 days in 春秋两季.": "按说明稀释肥料；春秋两季每 10-15 天施一次。",
		"按说明稀释肥料; apply once a month in spring.": "按说明稀释肥料；春季每月施一次。",
		"按说明稀释肥料; apply once a month in 春秋两季.": "按说明稀释肥料；春秋两季每月施一次。",
		"按说明稀释肥料; apply once a month, except in summer.": "按说明稀释肥料；每月施一次，夏季除外。",
		"按说明稀释肥料; apply once a month.": "按说明稀释肥料，每月施一次。",
		"按说明稀释肥料; apply once every 15 days from April to September.": "按说明稀释肥料；四月至九月每 15 天施一次。",
		"按说明稀释肥料; apply once or twice a month in 春秋两季.": "按说明稀释肥料；春秋两季每月施 1-2 次。",
		"按说明稀释肥料; apply 液态肥料s 1-2 times per month.": "按说明稀释肥料；每月施 1-2 次液态肥。",
		"按说明稀释肥料; 每月施1-2次 in spring.": "按说明稀释肥料；春季每月施 1-2 次。",
		"按说明稀释肥料; 每月施1-2次, excluding flowering stages.": "按说明稀释肥料；每月施 1-2 次，花期除外。",
		"按说明稀释肥料; 每月施一次 from spring to autumn.": "按说明稀释肥料；春秋两季每月施一次。",
		"按说明稀释肥料; 每月施一次 in early summer, spring, and autumn.": "按说明稀释肥料；春夏秋每月施一次。",
		"按说明稀释肥料; 每月施一次 in early summer, spring, and autumn; skip during winter dormancy.": "按说明稀释肥料；春夏秋每月施一次；冬季休眠期停肥。",
		"按说明稀释肥料; 每月施一次 in 春秋两季 only.": "按说明稀释肥料；仅春秋两季每月施一次。",
		"按说明稀释肥料，春秋两季每月施1-2次, except during flowering.": "按说明稀释肥料，春秋两季每月施 1-2 次，花期除外。",
		"按说明稀释肥料，每月施1-2次 pre-flowering; reduce in summer.": "按说明稀释肥料，花前每月施 1-2 次；夏季减少施肥。",
		"按说明稀释肥料，每月施一次 in spring, summer, and fall.": "按说明稀释肥料，春夏秋每月施一次。",
		"按说明稀释肥料，每月施一次 in 春秋两季.": "按说明稀释肥料，春秋两季每月施一次。",
		"按说明稀释肥料，每月施一次 to every two months.": "按说明稀释肥料，每 1-2 个月施一次。",
	},
	"修剪": {
		"After flowering, remove wilted flowers; the plant sprouts again in spring as parts wither in winter.": "花后剪去残花；部分枝条冬季枯萎，春季重新萌发。",
		"After flowering, remove withered parts; leave bulbs for next year's germination.": "花后去除枯萎部分；保留球根供来年萌发。",
		"After flowers fade, place in a shaded area; when leaves turn yellow, remove withered parts, keep tubers for next year.": "花后置于阴凉处；叶片变黄后去除枯萎部分，保留块根供来年种植。",
		"Prune dead, rotten, diseased, and unattractive parts.": "剪去枯死、腐烂、病变及不美观的部分。",
		"Prune dead, yellow and withered blooms.": "剪去枯黄和凋萎的花枝。",
		"Prune excessive, dead, and diseased branches promptly.": "及时疏剪过密、枯死和病变枝条。",
		"Prune for favorite tree shapes.": "根据喜好修剪造型。",
		"Prune in spring, removing old, diseased, and dead leaves promptly.": "春季修剪，及时去除老叶、病叶和枯叶。",
		"Prune withered, dead leaves and excessive daughter plants": "剪去枯叶、死叶及过多的分株",
		"Remove aged, dead, rotten, diseased tissues promptly. Clean rotted roots if planted in water.": "及时去除老化、枯死、腐烂、病变组织。水培时清理烂根。",
		"Remove aged, yellowing, and diseased leaves promptly": "及时去除老化、发黄和病变的叶片",
		"Remove dead and rotten leaves promptly; resistant to pruning.": "及时去除枯叶和烂叶；耐修剪。",
		"Remove dead and rotten parts timely.": "及时去除枯死和腐烂部分。",
		"Remove dead, yellow and diseased leaves promptly": "及时去除枯叶、黄叶和病叶",
		"Remove diseased, yellowing, and dropped leaves": "去除病变、发黄和脱落的叶片",
		"Remove flower stems, diseased, and rotten leaves promptly.": "及时剪去花茎、病叶和烂叶。",
		"Remove old tissues, dead, and pests' branches promptly": "及时去除老组织、枯枝和虫害枝条",
		"Remove rotten roots, old diseased, and dead leaves promptly.": "及时去除烂根、老病叶和枯叶。",
		"Remove sick, yellow leaves; pinch twice for branching.": "去除黄叶、病叶；摘心两次促分枝。",
		"Remove wilted flowers and ailing foliage; trim pedicels to 10cm after blooming, retaining only the basal 2-3 sections.": "去除凋萎花朵和萎蔫叶片；花后将花梗剪至 10cm，仅保留基部 2-3 节。",
		"Timely pruning for good canopy shape.": "及时修剪以保持良好株型。",
		"Timely remove aged, dead, rotten, diseased leaves.": "及时去除老化、枯死、腐烂、病变叶片。",
		"Timely remove dead and diseased branches.": "及时去除枯枝和病枝。",
		"Timely remove dead andyellowish leaves.": "及时去除枯叶和发黄叶片。",
		"Timely remove old, diseased, dead leaves and withered flowers.": "及时去除老叶、病叶、枯叶和残花。",
		"Timely remove withered flowers, old, diseased, and dead leaves.": "及时去除残花、老叶、病叶和枯叶。",
		"Timely remove yellowing leaves and withered flowers.": "及时去除黄叶和残花。",
		"清除老叶、病叶和枯叶 after flowering. Cut the upper part, starting 5 cm above soil surface, leaving 3-5 leaves.": "花后清除老叶、病叶和枯叶。从土面上方 5cm 处剪去上部，保留 3-5 片叶。",
	},
}

// translateCare 将 care 描述从英文翻译为中文。
// 按整句匹配：精确命中映射表则替换，未命中则尝试子串替换（处理中英混合句）。
func translateCare(label, value string) string {
	dict, ok := careTranslation[label]
	if !ok || strings.TrimSpace(value) == "" {
		return value
	}
	v := strings.TrimSpace(value)
	// 精确匹配
	if zh, hit := dict[v]; hit {
		return zh
	}
	// 子串替换（处理中英混合句，如"按说明稀释肥料; apply once a month"）
	bestKey, bestLen := "", 0
	for eng := range dict {
		if len(eng) > bestLen && strings.Contains(v, eng) {
			bestKey, bestLen = eng, len(eng)
		}
	}
	if bestKey != "" {
		return strings.ReplaceAll(v, bestKey, dict[bestKey])
	}
	return v
}