package services

// 本文件维护「中文名 → 拉丁学名」本地映射表。
//
// 背景：Open Plantbook 的 search 接口按 display_pid / alias(学名) /
// common names 检索，但库内中文 common name 覆盖极低，中文名几乎无法
// 直接命中；因此中文关键词先经此表转换为学名再查询。
// 学名沿用 Plantbook 数据库广泛采用的传统命名（而非最新分类修订），
// 以最大化命中率。别名（同一植物多个中文名）允许指向同一学名。

// PlantAlias 中文名-学名条目
type PlantAlias struct {
	Zh    string // 中文名（或常见别名）
	Latin string // 拉丁学名（Plantbook 检索键）
}

var zhToLatin = map[string]string{}

func init() {
	for _, a := range plantAliases {
		if _, exists := zhToLatin[a.Zh]; !exists {
			zhToLatin[a.Zh] = a.Latin
		}
	}
}

// lookupLatin 中文名转学名；命中返回 true
func lookupLatin(zh string) (string, bool) {
	latin, ok := zhToLatin[zh]
	return latin, ok
}

// plantAliases 中文名-学名对应表（搜索转换与批量同步共用数据源）
var plantAliases = []PlantAlias{
	// ---- 室内观叶 ----
	{"绿萝", "epipremnum aureum"},
	{"黄金葛", "epipremnum aureum"},
	{"麒麟叶", "epipremnum pinnatum"},
	{"龟背竹", "monstera deliciosa"},
	{"龟背芋", "monstera deliciosa"},
	{"仙洞龟背竹", "monstera adansonii"},
	{"蔓绿绒", "philodendron"},
	{"心叶蔓绿绒", "philodendron hederaceum"},
	{"红宝石喜林芋", "philodendron erubescens"},
	{"绿宝石喜林芋", "philodendron erubescens"},
	{"金钻", "philodendron erubescens"},
	{"春羽", "philodendron bipinnatifidum"},
	{"小天使", "philodendron xanadu"},
	{"虎皮兰", "sansevieria trifasciata"},
	{"虎尾兰", "sansevieria trifasciata"},
	{"圆叶虎尾兰", "sansevieria cylindrica"},
	{"白掌", "spathiphyllum wallisii"},
	{"白鹤芋", "spathiphyllum wallisii"},
	{"绿巨人", "spathiphyllum"},
	{"红掌", "anthurium andraeanum"},
	{"火鹤花", "anthurium andraeanum"},
	{"水晶花烛", "anthurium crystallinum"},
	{"海芋", "alocasia macrorrhizos"},
	{"滴水观音", "alocasia macrorrhizos"},
	{"黑叶观音莲", "alocasia"},
	{"琴叶榕", "ficus lyrata"},
	{"橡皮树", "ficus elastica"},
	{"印度榕", "ficus elastica"},
	{"垂叶榕", "ficus benjamina"},
	{"榕树", "ficus microcarpa"},
	{"人参榕", "ficus microcarpa"},
	{"菩提树", "ficus religiosa"},
	{"吊兰", "chlorophytum comosum"},
	{"富贵竹", "dracaena sanderiana"},
	{"巴西木", "dracaena fragrans"},
	{"巴西铁", "dracaena fragrans"},
	{"千年木", "dracaena marginata"},
	{"龙血树", "dracaena"},
	{"百合竹", "dracaena reflexa"},
	{"酒瓶兰", "beaucarnea recurvata"},
	{"荷兰铁", "yucca elephantipes"},
	{"丝兰", "yucca"},
	{"朱蕉", "cordyline fruticosa"},
	{"也门铁", "dracaena arborea"},
	{"金钱树", "zamioculcas zamiifolia"},
	{"平安树", "cinnamomum kotoense"},
	{"兰屿肉桂", "cinnamomum kotoense"},
	{"发财树", "pachira aquatica"},
	{"鹅掌柴", "schefflera arboricola"},
	{"鹅掌藤", "schefflera arboricola"},
	{"鸭脚木", "schefflera heptaphylla"},
	{"昆士兰伞木", "schefflera actinophylla"},
	{"大叶伞", "schefflera actinophylla"},
	{"八角金盘", "fatsia japonica"},
	{"福禄桐", "polyscias"},
	{"圆叶福禄桐", "polyscias scutellaria"},
	{"羽叶福禄桐", "polyscias fruticosa"},
	{"文竹", "asparagus setaceus"},
	{"武竹", "asparagus densiflorus"},
	{"君子兰", "clivia miniata"},
	{"垂笑君子兰", "clivia nobilis"},
	{"常春藤", "hedera helix"},
	{"洋常春藤", "hedera helix"},
	{"铜钱草", "hydrocotyle vulgaris"},
	{"合果芋", "syngonium podophyllum"},
	{"白蝴蝶", "syngonium podophyllum"},
	{"广东万年青", "aglaonema modestum"},
	{"粗肋草", "aglaonema"},
	{"万年青", "rohdea japonica"},
	{"花叶万年青", "dieffenbachia seguine"},
	{"黛粉叶", "dieffenbachia seguine"},
	{"一叶兰", "aspidistra elatior"},
	{"蜘蛛抱蛋", "aspidistra elatior"},
	{"竹芋", "maranta leuconeura"},
	{"孔雀竹芋", "calathea makoyana"},
	{"双线竹芋", "calathea ornata"},
	{"天鹅绒竹芋", "calathea zebrina"},
	{"青苹果竹芋", "calathea orbifolia"},
	{"鹤望兰", "strelitzia reginae"},
	{"天堂鸟", "strelitzia reginae"},
	{"尼古拉鹤望兰", "strelitzia nicolai"},
	{"旅人蕉", "ravenala madagascariensis"},
	{"袖珍椰子", "chamaedorea elegans"},
	{"夏威夷椰子", "chamaedorea seifrizii"},
	{"散尾葵", "dypsis lutescens"},
	{"国王椰子", "ravenea rivularis"},
	{"棕竹", "rhapis excelsa"},
	{"金山棕", "rhapis excelsa"},
	{"蒲葵", "livistona chinensis"},
	{"苏铁", "cycas revoluta"},
	{"南洋杉", "araucaria heterophylla"},
	{"罗汉松", "podocarpus macrophyllus"},
	{"竹柏", "nageia nagi"},
	{"镜面草", "pilea peperomioides"},
	{"冷水花", "pilea cadierei"},
	{"豆瓣绿", "peperomia obtusifolia"},
	{"圆叶椒草", "peperomia obtusifolia"},
	{"西瓜皮椒草", "peperomia argyreia"},
	{"皱叶椒草", "peperomia caperata"},
	{"吊竹梅", "tradescantia zebrina"},
	{"紫露草", "tradescantia"},
	{"口红吊兰", "aeschynanthus radicans"},
	{"金鱼吊兰", "nematanthus"},
	{"牡丹吊兰", "aptenia cordifolia"},
	{"嫣红蔓", "hypoestes phyllostachya"},
	{"网纹草", "fittonia albivenis"},
	{"红网纹草", "fittonia albivenis"},
	{"鸟巢蕨", "asplenium nidus"},
	{"巢蕨", "asplenium nidus"},
	{"波士顿蕨", "nephrolepis exaltata"},
	{"肾蕨", "nephrolepis cordifolia"},
	{"铁线蕨", "adiantum capillus-veneris"},
	{"鹿角蕨", "platycerium"},
	{"狼尾蕨", "davallia trichomanoides"},
	{"凤尾蕨", "pteris cretica"},
	{"翠云草", "selaginella uncinata"},

	// ---- 多肉 / 仙人掌 ----
	{"芦荟", "aloe vera"},
	{"库拉索芦荟", "aloe vera"},
	{"十二卷", "haworthia"},
	{"条纹十二卷", "haworthia fasciata"},
	{"玉露", "haworthia cooperi"},
	{"玉扇", "haworthia truncata"},
	{"万象", "haworthia maughanii"},
	{"龙舌兰", "agave americana"},
	{"狐尾龙舌兰", "agave attenuata"},
	{"金边龙舌兰", "agave americana"},
	{"玉树", "crassula ovata"},
	{"燕子掌", "crassula ovata"},
	{"茜之塔", "crassula capitella"},
	{"青锁龙", "crassula muscosa"},
	{"钱串", "crassula perforata"},
	{"石莲花", "echeveria"},
	{"玉蝶", "echeveria elegans"},
	{"静夜", "echeveria derenbergii"},
	{"吉娃莲", "echeveria chihuahuaensis"},
	{"桃美人", "pachyphytum oviferum"},
	{"冬美人", "graptopetalum paraguayense"},
	{"胧月", "graptopetalum paraguayense"},
	{"姬秋丽", "graptopetalum mendozae"},
	{"虹之玉", "sedum rubrotinctum"},
	{"乙女心", "sedum pachyphyllum"},
	{"薄雪万年草", "sedum hispanicum"},
	{"垂盆草", "sedum sarmentosum"},
	{"佛甲草", "sedum lineare"},
	{"观音莲", "sempervivum tectorum"},
	{"长生草", "sempervivum"},
	{"山地玫瑰", "aeonium"},
	{"黑法师", "aeonium arboreum"},
	{"莲花掌", "aeonium"},
	{"长寿花", "kalanchoe blossfeldiana"},
	{"月兔耳", "kalanchoe tomentosa"},
	{"唐印", "kalanchoe thyrsiflora"},
	{"落地生根", "kalanchoe daigremontiana"},
	{"熊童子", "cotyledon tomentosa"},
	{"福娘", "cotyledon orbiculata"},
	{"生石花", "lithops"},
	{"帝玉", "pleiospilos nelii"},
	{"肉锥", "conophytum"},
	{"金枝玉叶", "portulacaria afra"},
	{"马齿苋树", "portulacaria afra"},
	{"非洲霸王树", "pachypodium lamerei"},
	{"沙漠玫瑰", "adenium obesum"},
	{"鸡蛋花", "plumeria rubra"},
	{"龟甲龙", "dioscorea elephantipes"},
	{"仙人掌", "opuntia"},
	{"梨果仙人掌", "opuntia ficus-indica"},
	{"黄毛掌", "opuntia microdasys"},
	{"仙人球", "echinopsis oxygona"},
	{"绯花玉", "gymnocalycium baldianum"},
	{"金琥", "echinocactus grusonii"},
	{"量天尺", "hylocereus undatus"},
	{"火龙果", "hylocereus undatus"},
	{"昙花", "epiphyllum oxypetalum"},
	{"令箭荷花", "disocactus ackermannii"},
	{"鼠尾掌", "aporocactus flagelliformis"},
	{"蟹爪兰", "schlumbergera truncata"},
	{"仙人指", "schlumbergera bridgesii"},
	{"星球", "astrophytum asterias"},
	{"鸾凤玉", "astrophytum myriostigma"},
	{"般若", "astrophytum ornatum"},
	{"乳突球", "mammillaria"},
	{"金手指", "mammillaria elongata"},
	{"翁柱", "cephalocereus senilis"},
	{"麒麟掌", "euphorbia lactea"},
	{"龙骨", "euphorbia trigona"},
	{"霸王鞭", "euphorbia royleana"},
	{"光棍树", "euphorbia tirucalli"},
	{"一品红", "euphorbia pulcherrima"},
	{"虎刺梅", "euphorbia milii"},
	{"铁海棠", "euphorbia milii"},
	{"佛肚树", "jatropha podagrica"},

	// ---- 观花植物 ----
	{"蝴蝶兰", "phalaenopsis"},
	{"石斛兰", "dendrobium nobile"},
	{"文心兰", "oncidium"},
	{"大花蕙兰", "cymbidium"},
	{"卡特兰", "cattleya"},
	{"兜兰", "paphiopedilum"},
	{"春兰", "cymbidium goeringii"},
	{"建兰", "cymbidium ensifolium"},
	{"墨兰", "cymbidium sinense"},
	{"蕙兰", "cymbidium faberi"},
	{"寒兰", "cymbidium kanran"},
	{"仙客来", "cyclamen persicum"},
	{"丽格海棠", "begonia elatior"},
	{"四季海棠", "begonia semperflorens"},
	{"蟆叶海棠", "begonia rex"},
	{"球根海棠", "begonia tuberhybrida"},
	{"竹节秋海棠", "begonia corallina"},
	{"擎天凤梨", "guzmania"},
	{"红运当头", "guzmania"},
	{"莺歌凤梨", "vriesea"},
	{"空气凤梨", "tillandsia"},
	{"紫花凤梨", "tillandsia cyanea"},
	{"铁兰", "tillandsia cyanea"},
	{"积水凤梨", "neoregelia"},
	{"姬凤梨", "cryptanthus"},
	{"观赏凤梨", "bromelia"},
	{"天竺葵", "pelargonium hortorum"},
	{"盾叶天竺葵", "pelargonium peltatum"},
	{"香叶天竺葵", "pelargonium graveolens"},
	{"倒挂金钟", "fuchsia hybrida"},
	{"矮牵牛", "petunia"},
	{"百万小铃", "calibrachoa"},
	{"舞春花", "calibrachoa"},
	{"太阳花", "portulaca grandiflora"},
	{"半支莲", "portulaca grandiflora"},
	{"勋章菊", "gazania rigens"},
	{"五色梅", "lantana camara"},
	{"美女樱", "verbena"},
	{"百日草", "zinnia elegans"},
	{"波斯菊", "cosmos bipinnatus"},
	{"硫华菊", "cosmos sulphureus"},
	{"万寿菊", "tagetes erecta"},
	{"孔雀草", "tagetes patula"},
	{"向日葵", "helianthus annuus"},
	{"翠菊", "callistephus chinensis"},
	{"雏菊", "bellis perennis"},
	{"三色堇", "viola tricolor"},
	{"角堇", "viola cornuta"},
	{"紫罗兰", "matthiola incana"},
	{"虞美人", "papaver rhoeas"},
	{"花菱草", "eschscholzia californica"},
	{"石竹", "dianthus chinensis"},
	{"康乃馨", "dianthus caryophyllus"},
	{"满天星", "gypsophila paniculata"},
	{"勿忘我", "myosotis sylvatica"},
	{"风信子", "hyacinthus orientalis"},
	{"郁金香", "tulipa"},
	{"洋水仙", "narcissus pseudonarcissus"},
	{"水仙", "narcissus"},
	{"中国水仙", "narcissus tazetta"},
	{"葡萄风信子", "muscari botryoides"},
	{"番红花", "crocus sativus"},
	{"藏红花", "crocus sativus"},
	{"小苍兰", "freesia"},
	{"鸢尾", "iris"},
	{"德国鸢尾", "iris germanica"},
	{"马蔺", "iris lactea"},
	{"百合", "lilium"},
	{"麝香百合", "lilium longiflorum"},
	{"卷丹", "lilium lancifolium"},
	{"朱顶红", "hippeastrum"},
	{"葱兰", "zephyranthes candida"},
	{"风雨兰", "zephyranthes"},
	{"六出花", "alstroemeria"},
	{"大丽花", "dahlia"},
	{"美人蕉", "canna indica"},
	{"姜花", "hedychium coronarium"},
	{"姜荷花", "curcuma alismatifolia"},
	{"马蹄莲", "zantedeschia aethiopica"},
	{"风铃草", "campanula"},
	{"耧斗菜", "aquilegia"},
	{"玉簪", "hosta"},
	{"萱草", "hemerocallis"},
	{"黄花菜", "hemerocallis citrina"},
	{"麦冬", "ophiopogon japonicus"},
	{"铃兰", "convallaria majalis"},
	{"唐菖蒲", "gladiolus"},
	{"剑兰", "gladiolus"},
	{"石蒜", "lycoris radiata"},
	{"彼岸花", "lycoris radiata"},
	{"荷包牡丹", "dicentra spectabilis"},
	{"矾根", "heuchera"},
	{"铁筷子", "helleborus"},
	{"羽扇豆", "lupinus"},
	{"鲁冰花", "lupinus"},
	{"毛地黄", "digitalis purpurea"},
	{"金鱼草", "antirrhinum majus"},
	{"福禄考", "phlox"},
	{"紫松果菊", "echinacea purpurea"},
	{"黑心菊", "rudbeckia hirta"},
	{"金光菊", "rudbeckia"},
	{"蛇鞭菊", "liatris spicata"},
	{"飞燕草", "consolida ajacis"},
	{"翠雀", "delphinium grandiflorum"},
	{"香雪球", "lobularia maritima"},
	{"六倍利", "lobelia erinus"},
	{"凤仙花", "impatiens balsamina"},
	{"非洲凤仙", "impatiens walleriana"},
	{"新几内亚凤仙", "impatiens hawkeri"},
	{"报春花", "primula malacoides"},
	{"欧洲报春", "primula vulgaris"},
	{"大岩桐", "sinningia speciosa"},
	{"非洲堇", "saintpaulia ionantha"},
	{"猪笼草", "nepenthes"},
	{"捕蝇草", "dionaea muscipula"},
	{"瓶子草", "sarracenia"},
	{"茅膏菜", "drosera"},
	{"旱金莲", "tropaeolum majus"},
	{"紫茉莉", "mirabilis jalapa"},
	{"长春花", "catharanthus roseus"},
	{"飘香藤", "mandevilla sanderi"},
	{"蓝雪花", "plumbago auriculata"},
	{"茑萝", "ipomoea quamoclit"},
	{"牵牛花", "ipomoea nil"},
	{"圆叶牵牛", "ipomoea purpurea"},

	// ---- 木本花卉 ----
	{"月季", "rosa chinensis"},
	{"玫瑰", "rosa rugosa"},
	{"蔷薇", "rosa multiflora"},
	{"木香花", "rosa banksiae"},
	{"茉莉", "jasminum sambac"},
	{"素馨", "jasminum grandiflorum"},
	{"迎春花", "jasminum nudiflorum"},
	{"丁香", "syringa vulgaris"},
	{"桂花", "osmanthus fragrans"},
	{"栀子花", "gardenia jasminoides"},
	{"六月雪", "serissa japonica"},
	{"狗牙花", "tabernaemontana divaricata"},
	{"夹竹桃", "nerium oleander"},
	{"络石", "trachelospermum jasminoides"},
	{"风车茉莉", "trachelospermum jasminoides"},
	{"九里香", "murraya paniculata"},
	{"米兰", "aglaia odorata"},
	{"米仔兰", "aglaia odorata"},
	{"金银花", "lonicera japonica"},
	{"金银木", "lonicera maackii"},
	{"凌霄", "campsis grandiflora"},
	{"美国凌霄", "campsis radicans"},
	{"炮仗花", "pyrostegia venusta"},
	{"使君子", "quisqualis indica"},
	{"木槿", "hibiscus syriacus"},
	{"扶桑", "hibiscus rosa-sinensis"},
	{"朱槿", "hibiscus rosa-sinensis"},
	{"芙蓉葵", "hibiscus moscheutos"},
	{"木芙蓉", "hibiscus mutabilis"},
	{"蜀葵", "alcea rosea"},
	{"三角梅", "bougainvillea glabra"},
	{"叶子花", "bougainvillea spectabilis"},
	{"绣球", "hydrangea macrophylla"},
	{"八仙花", "hydrangea macrophylla"},
	{"圆锥绣球", "hydrangea paniculata"},
	{"木绣球", "viburnum macrocephalum"},
	{"瑞香", "daphne odora"},
	{"结香", "edgeworthia chrysantha"},
	{"含笑", "michelia figo"},
	{"白兰", "magnolia alba"},
	{"玉兰", "magnolia denudata"},
	{"紫玉兰", "magnolia liliiflora"},
	{"广玉兰", "magnolia grandiflora"},
	{"腊梅", "chimonanthus praecox"},
	{"蜡梅", "chimonanthus praecox"},
	{"梅花", "prunus mume"},
	{"桃花", "prunus persica"},
	{"碧桃", "prunus persica"},
	{"樱花", "prunus serrulata"},
	{"东京樱花", "prunus yedoensis"},
	{"榆叶梅", "prunus triloba"},
	{"紫叶李", "prunus cerasifera"},
	{"紫薇", "lagerstroemia indica"},
	{"杜鹃", "rhododendron simsii"},
	{"映山红", "rhododendron simsii"},
	{"西洋杜鹃", "rhododendron"},
	{"山茶", "camellia japonica"},
	{"茶花", "camellia japonica"},
	{"茶梅", "camellia sasanqua"},
	{"金花茶", "camellia nitidissima"},
	{"牡丹", "paeonia suffruticosa"},
	{"芍药", "paeonia lactiflora"},
	{"连翘", "forsythia suspensa"},
	{"海棠花", "malus spectabilis"},
	{"西府海棠", "malus micromalus"},
	{"垂丝海棠", "malus halliana"},
	{"贴梗海棠", "chaenomeles speciosa"},
	{"木瓜海棠", "chaenomeles cathayensis"},
	{"棣棠", "kerria japonica"},
	{"绣线菊", "spiraea"},
	{"珍珠梅", "sorbaria sorbifolia"},
	{"黄刺玫", "rosa xanthina"},
	{"紫荆", "cercis chinensis"},
	{"加拿大紫荆", "cercis canadensis"},
	{"羊蹄甲", "bauhinia purpurea"},
	{"洋紫荆", "bauhinia variegata"},
	{"红花羊蹄甲", "bauhinia blakeana"},
	{"凤凰木", "delonix regia"},
	{"合欢", "albizia julibrissin"},
	{"紫藤", "wisteria sinensis"},
	{"龙吐珠", "clerodendrum thomsoniae"},
	{"赪桐", "clerodendrum japonicum"},
	{"金缕梅", "hamamelis"},

	// ---- 香草 / 香料 ----
	{"罗勒", "ocimum basilicum"},
	{"九层塔", "ocimum basilicum"},
	{"迷迭香", "rosmarinus officinalis"},
	{"薄荷", "mentha haplocalyx"},
	{"留兰香", "mentha spicata"},
	{"绿薄荷", "mentha spicata"},
	{"胡椒薄荷", "mentha piperita"},
	{"香菜", "coriandrum sativum"},
	{"芫荽", "coriandrum sativum"},
	{"茴香", "foeniculum vulgare"},
	{"莳萝", "anethum graveolens"},
	{"百里香", "thymus vulgaris"},
	{"牛至", "origanum vulgare"},
	{"披萨草", "origanum vulgare"},
	{"马郁兰", "origanum majorana"},
	{"鼠尾草", "salvia officinalis"},
	{"蓝花鼠尾草", "salvia farinacea"},
	{"薰衣草", "lavandula angustifolia"},
	{"紫苏", "perilla frutescens"},
	{"细香葱", "allium schoenoprasum"},
	{"虾夷葱", "allium schoenoprasum"},
	{"香茅", "cymbopogon citratus"},
	{"柠檬香蜂草", "melissa officinalis"},
	{"猫薄荷", "nepeta cataria"},
	{"藿香", "agastache rugosa"},
	{"碰碰香", "plectranthus tomentosa"},

	// ---- 蔬菜 ----
	{"番茄", "solanum lycopersicum"},
	{"西红柿", "solanum lycopersicum"},
	{"小番茄", "solanum lycopersicum"},
	{"圣女果", "solanum lycopersicum"},
	{"樱桃番茄", "solanum lycopersicum"},
	{"茄子", "solanum melongena"},
	{"辣椒", "capsicum annuum"},
	{"甜椒", "capsicum annuum"},
	{"彩椒", "capsicum annuum"},
	{"土豆", "solanum tuberosum"},
	{"马铃薯", "solanum tuberosum"},
	{"红薯", "ipomoea batatas"},
	{"花生", "arachis hypogaea"},
	{"玉米", "zea mays"},
	{"黄瓜", "cucumis sativus"},
	{"甜瓜", "cucumis melo"},
	{"哈密瓜", "cucumis melo"},
	{"西瓜", "citrullus lanatus"},
	{"南瓜", "cucurbita"},
	{"西葫芦", "cucurbita pepo"},
	{"苦瓜", "momordica charantia"},
	{"丝瓜", "luffa aegyptiaca"},
	{"冬瓜", "benincasa hispida"},
	{"葫芦", "lagenaria siceraria"},
	{"佛手瓜", "sechium edule"},
	{"四季豆", "phaseolus vulgaris"},
	{"芸豆", "phaseolus vulgaris"},
	{"豇豆", "vigna unguiculata"},
	{"豌豆", "pisum sativum"},
	{"蚕豆", "vicia faba"},
	{"毛豆", "glycine max"},
	{"大豆", "glycine max"},
	{"扁豆", "lablab purpureus"},
	{"菠菜", "spinacia oleracea"},
	{"生菜", "lactuca sativa"},
	{"芹菜", "apium graveolens"},
	{"胡萝卜", "daucus carota"},
	{"萝卜", "raphanus sativus"},
	{"樱桃萝卜", "raphanus sativus"},
	{"白菜", "brassica rapa"},
	{"小白菜", "brassica rapa"},
	{"上海青", "brassica rapa"},
	{"西兰花", "brassica oleracea"},
	{"花椰菜", "brassica oleracea"},
	{"卷心菜", "brassica oleracea"},
	{"甘蓝", "brassica oleracea"},
	{"羽衣甘蓝", "brassica oleracea"},
	{"芥菜", "brassica juncea"},
	{"苋菜", "amaranthus tricolor"},
	{"空心菜", "ipomoea aquatica"},
	{"蕹菜", "ipomoea aquatica"},
	{"茼蒿", "glebionis coronaria"},
	{"木耳菜", "basella alba"},
	{"落葵", "basella alba"},
	{"秋葵", "abelmoschus esculentus"},
	{"芝麻菜", "eruca vesicaria"},
	{"韭菜", "allium tuberosum"},
	{"洋葱", "allium cepa"},
	{"大蒜", "allium sativum"},
	{"葱", "allium fistulosum"},
	{"生姜", "zingiber officinale"},

	// ---- 果树 ----
	{"草莓", "fragaria ananassa"},
	{"蓝莓", "vaccinium corymbosum"},
	{"树莓", "rubus idaeus"},
	{"覆盆子", "rubus idaeus"},
	{"黑莓", "rubus fruticosus"},
	{"桑葚", "morus alba"},
	{"葡萄", "vitis vinifera"},
	{"提子", "vitis vinifera"},
	{"猕猴桃", "actinidia chinensis"},
	{"奇异果", "actinidia chinensis"},
	{"苹果", "malus domestica"},
	{"梨", "pyrus"},
	{"桃", "prunus persica"},
	{"油桃", "prunus persica"},
	{"李子", "prunus salicina"},
	{"杏", "prunus armeniaca"},
	{"樱桃", "prunus cerasus"},
	{"车厘子", "prunus avium"},
	{"枣", "ziziphus jujuba"},
	{"柿子", "diospyros kaki"},
	{"无花果", "ficus carica"},
	{"石榴", "punica granatum"},
	{"橙子", "citrus sinensis"},
	{"橘子", "citrus reticulata"},
	{"柑橘", "citrus reticulata"},
	{"柚子", "citrus maxima"},
	{"柠檬", "citrus limon"},
	{"青柠", "citrus aurantiifolia"},
	{"金桔", "citrus japonica"},
	{"佛手", "citrus medica"},
	{"百香果", "passiflora edulis"},
	{"西番莲", "passiflora edulis"},
	{"芒果", "mangifera indica"},
	{"荔枝", "litchi chinensis"},
	{"龙眼", "dimocarpus longan"},
	{"枇杷", "eriobotrya japonica"},
	{"杨梅", "myrica rubra"},
	{"香蕉", "musa"},
	{"芭蕉", "musa basjoo"},
	{"番木瓜", "carica papaya"},
	{"菠萝", "ananas comosus"},
	{"椰子", "cocos nucifera"},
	{"牛油果", "persea americana"},
	{"鳄梨", "persea americana"},
	{"咖啡", "coffea arabica"},
	{"山楂", "crataegus pinnatifida"},
	{"核桃", "juglans regia"},
	{"板栗", "castanea mollissima"},
	{"银杏", "ginkgo biloba"},

	// ---- 水生 / 湿生 ----
	{"荷花", "nelumbo nucifera"},
	{"碗莲", "nelumbo nucifera"},
	{"睡莲", "nymphaea"},
	{"王莲", "victoria amazonica"},
	{"一叶莲", "nymphoides hydrophylla"},
	{"荇菜", "nymphoides"},
	{"水葫芦", "eichhornia crassipes"},
	{"菖蒲", "acorus calamus"},
	{"石菖蒲", "acorus gramineus"},
	{"再力花", "thalia dealbata"},
	{"梭鱼草", "pontederia cordata"},
	{"千屈菜", "lythrum salicaria"},
	{"慈姑", "sagittaria sagittifolia"},
	{"芡实", "euryale ferox"},
	{"灯心草", "juncus effusus"},
	{"旱伞草", "cyperus alternifolius"},
	{"水竹", "cyperus alternifolius"},

	// ---- 地被 / 草坪 ----
	{"狗牙根", "cynodon dactylon"},
	{"结缕草", "zoysia japonica"},
	{"马尼拉草", "zoysia matrella"},
	{"高羊茅", "festuca arundinacea"},
	{"黑麦草", "lolium perenne"},
	{"早熟禾", "poa pratensis"},
	{"三叶草", "trifolium repens"},
	{"白车轴草", "trifolium repens"},
}
